import type { ReactNode } from 'react'
import {
  Radar,
  Zap,
  EyeOff,
  Waves,
  ArrowUp,
  Footprints,
  Users,
  Telescope,
  Circle,
  Wind,
  Shield,
  Moon,
  Cylinder,
  Gauge,
  Plane,
  AlertTriangle,
  Sun,
  PauseCircle,
  Diamond,
  Droplet,
  Eye,
  Ghost,
  ArrowRight,
  BarChart,
  VolumeX,
  Repeat,
  Star,
  Sparkles,
  Square,
  Atom,
} from 'lucide-react'
import type { PhysicalCharacteristic } from '../data/events'

const sizeClass = 'w-3 h-3'

/** Shared characteristic → Lucide icon map — must cover every PhysicalCharacteristic */
export const characteristicIconMap: Record<PhysicalCharacteristic, ReactNode> = {
  'instantaneous-acceleration': <Zap className={sizeClass} />,
  'low-observability': <EyeOff className={sizeClass} />,
  'transmedium': <Waves className={sizeClass} />,
  'anti-gravity': <ArrowUp className={sizeClass} />,
  'multi-sensor': <Radar className={sizeClass} />,
  'electromagnetic': <Zap className={sizeClass} />,
  'physical-traces': <Footprints className={sizeClass} />,
  'nuclear-association': <Atom className={sizeClass} />,
  'group-sighting': <Users className={sizeClass} />,
  'space': <Telescope className={sizeClass} />,
  'orb-spherical': <Circle className={sizeClass} />,
  'high-speed': <Wind className={sizeClass} />,
  'impact-resistant': <Shield className={sizeClass} />,
  'missile-deflection': <Shield className={sizeClass} />,
  'transmedium-suspected': <Waves className={sizeClass} />,
  'dark-colored': <Moon className={sizeClass} />,
  'football-sized': <Circle className={sizeClass} />,
  'cylindrical': <Cylinder className={sizeClass} />,
  'mach-2+': <Gauge className={sizeClass} />,
  'transited-under-wing': <Plane className={sizeClass} />,
  'near-miss': <AlertTriangle className={sizeClass} />,
  'flight-safety-hazard': <AlertTriangle className={sizeClass} />,
  'metallic': <Shield className={sizeClass} />,
  'commercial-airplane-size': <Plane className={sizeClass} />,
  'stationary-hover': <PauseCircle className={sizeClass} />,
  'bright-white-light': <Sun className={sizeClass} />,
  'sudden-disappearance': <EyeOff className={sizeClass} />,
  'diamond-shaped': <Diamond className={sizeClass} />,
  'inverted-teardrop': <Droplet className={sizeClass} />,
  'only-swir-visible': <Eye className={sizeClass} />,
  'high-speed-434-knots': <Wind className={sizeClass} />,
  'stealth-spectrum-selective': <Ghost className={sizeClass} />,
  'straight-flight-path': <ArrowRight className={sizeClass} />,
  'constant-altitude': <BarChart className={sizeClass} />,
  'faster-than-conventional-aircraft': <Gauge className={sizeClass} />,
  'sustained-high-speed': <Wind className={sizeClass} />,
  'silver': <Sun className={sizeClass} />,
  'orb': <Circle className={sizeClass} />,
  'silent': <VolumeX className={sizeClass} />,
  'repeated-sighting': <Repeat className={sizeClass} />,
  'star-shaped-contrast': <Star className={sizeClass} />,
  'green-fireball': <Sparkles className={sizeClass} />,
  'rectangular': <Square className={sizeClass} />,
}
